
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level

# rules that have both warning and error levels, can set just the warning level
# implicitly

# they can set both implicitly with an array

# or they can set both explicitly
  
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:

  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
